# Generated by Django 2.2.1 on 2019-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
